sudo: required
services:
  - docker

before_install:
  - docker build -t solderingknowledge/reactocker -f Dockerfile.dev .

script:
  - docker run -e CI=true solderingknowledge/reactocker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "reactocker"
  env: "Reactocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-919006835495"
  bucket_path: "reactocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY