sudo: required
services:
  - docker

before_install:
  - docker build -t solderingknowledge/reactocker -f Dockerfile.dev .

script:
  - docker run -e CI=true solderingknowledge/reactocker npm run test